//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    pub active_expires: i64,
    pub idle_expires: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::auth_user::Entity",
        from = "Column::UserId",
        to = "super::auth_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AuthUser,
}

impl Related<super::auth_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
